# Define the list of files to remove
$filesToRemove = @(
    "apps/admin/src/components/admin-layout.tsx",
    "apps/admin/src/components/breadcrumb.tsx",
    "apps/admin/src/components/command-menu.tsx",
    "apps/admin/src/components/locale-switcher.tsx",
    "apps/admin/src/components/rich-text-editor.tsx",
    "apps/admin/src/components/role-switcher.tsx",
    "apps/admin/src/hooks/use-autosave.ts",
    "apps/admin/src/hooks/use-dirty-warning.ts",
    "apps/admin/src/lib/api-client.ts",
    "apps/admin/src/lib/chat-persistence.ts",
    "apps/admin/src/lib/markdown-buffer.ts",
    "apps/admin/src/lib/permissions.ts",
    "apps/admin/src/lib/vipps.ts",
    "apps/admin/src/app/actions/admin.ts",
    "apps/admin/src/app/actions/all-members.ts",
    "apps/admin/src/app/actions/all-members.types.ts",
    "apps/admin/src/app/actions/benefit-analytics.ts",
    "apps/admin/src/app/actions/benefit-partners.ts",
    "apps/admin/src/app/actions/benefits.ts",
    "apps/admin/src/app/actions/campus.ts",
    "apps/admin/src/app/actions/events.ts",
    "apps/admin/src/app/actions/export-orders.ts",
    "apps/admin/src/app/actions/jobs.ts",
    "apps/admin/src/app/actions/membership-settings.ts",
    "apps/admin/src/app/actions/membership-sync.ts",
    "apps/admin/src/app/actions/new-member.ts",
    "apps/admin/src/app/actions/orders.ts",
    "apps/admin/src/app/actions/partners.ts",
    "apps/admin/src/app/actions/products.ts",
    "apps/admin/src/app/actions/shop-metrics.ts",
    "apps/admin/src/app/actions/varsling.ts",
    "apps/admin/src/components/admin/admin-summary.tsx",
    "apps/admin/src/components/assistant/assistant-message.tsx",
    "apps/admin/src/components/assistant/assistant-sidebar.tsx",
    "apps/admin/src/components/assistant/assistant-trigger.tsx",
    "apps/admin/src/components/assistant/use-chat-stream.ts",
    "apps/admin/src/components/dashboard/index.tsx",
    "apps/admin/src/components/forms/character-count.tsx",
    "apps/admin/src/components/forms/cover-image-upload.tsx",
    "apps/admin/src/components/forms/draft-restore-banner.tsx",
    "apps/admin/src/components/forms/form-section.tsx",
    "apps/admin/src/components/forms/locale-tab-group.tsx",
    "apps/admin/src/components/forms/save-bar.tsx",
    "apps/admin/src/components/forms/slugify.ts",
    "apps/admin/src/components/layout/admin-providers.tsx",
    "apps/admin/src/components/notifications/notifications-provider.tsx",
    "apps/admin/src/components/preview/event-preview-pane.tsx",
    "apps/admin/src/components/preview/job-preview-pane.tsx",
    "apps/admin/src/components/preview/news-preview-pane.tsx",
    "apps/admin/src/components/preview/preview-panel.tsx",
    "apps/admin/src/components/preview/product-preview-pane.tsx",
    "apps/admin/src/components/shared/animated-badge.tsx",
    "apps/admin/src/components/shared/glass-card.tsx",
    "apps/admin/src/components/shared/metric-card.tsx",
    "apps/admin/src/components/units/department-actions-header.tsx",
    "apps/admin/src/components/units/department-card.tsx",
    "apps/admin/src/components/units/department-editor-sidebar.tsx",
    "apps/admin/src/components/units/department-filters-wrapper.tsx",
    "apps/admin/src/components/units/department-filters.tsx",
    "apps/admin/src/components/units/department-skeleton.tsx",
    "apps/admin/src/components/units/department-stats.tsx",
    "apps/admin/src/components/units/departments-infinite-list.tsx",
    "apps/admin/src/components/units/hero-upload-preview.tsx",
    "apps/admin/src/components/units/logo-upload-preview.tsx",
    "apps/admin/src/components/units/units-hero-section.tsx",
    "apps/admin/src/lib/actions/admin-dashboard.ts",
    "apps/admin/src/lib/actions/departments.ts",
    "apps/admin/src/lib/admin/departments.ts",
    "apps/admin/src/lib/hooks/use-departments-filter.ts",
    "apps/admin/src/lib/utils/admin.ts",
    "apps/admin/src/lib/utils/content-translations.ts",
    "apps/admin/src/app/actions/pages/actions.ts",
    "apps/admin/src/app/actions/pages/seo.ts",
    "apps/admin/src/app/actions/pages/translate.ts",
    "apps/admin/src/app/actions/pages/types.ts",
    "apps/admin/src/app/actions/pages/utils.ts",
    "apps/admin/src/app/actions/shop/approval-actions.ts",
    "apps/admin/src/app/actions/_utils/all-members.utils.ts",
    "apps/admin/src/app/actions/_utils/translatable.ts"
)

foreach ($file in $filesToRemove) {
    if (Test-Path $file) {
        Write-Host "Removing: $file" -ForegroundColor Yellow
        # Remove -WhatIf to actually delete the files
        Remove-Item $file -Force
    } else {
        Write-Host "File not found: $file" -ForegroundColor Gray
    }
}