import type { Models } from "node-appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts ./types`.

export enum NotificationStatus {
  READ = "read",
  UNREAD = "unread",
}

export enum ExpenseStatus {
  DRAFT = "draft",
  PENDING = "pending",
  SUCCESS = "success",
  SUBMITTED = "submitted",
  REJECTED = "rejected",
}

export enum OrderStatus {
  PENDING = "pending",
  AUTHORIZED = "authorized",
  PAID = "paid",
  CANCELLED = "cancelled",
  FAILED = "failed",
  REFUNDED = "refunded",
}

export enum Currency {
  NOK = "NOK",
}

export enum AppNoticeLocale {
  NORWEGIAN = "norwegian",
  ENGLISH = "english",
}

export enum Condition {
  NEW = "new",
  LIKE_NEW = "like_new",
  GOOD = "good",
  FAIR = "fair",
  POOR = "poor",
}

export enum MarketplaceProductStatus {
  AVAILABLE = "available",
  SOLD = "sold",
  RESERVED = "reserved",
  INACTIVE = "inactive",
}

export enum ContactMethod {
  MESSAGE = "message",
  PHONE = "phone",
  EMAIL = "email",
}

export enum ChatType {
  DIRECT = "direct",
  GROUP = "group",
  TEAM = "team",
  DEPARTMENT = "department",
}

export enum ChatMessageType {
  TEXT = "text",
  IMAGE = "image",
  FILE = "file",
  SYSTEM = "system",
  PRODUCT = "product",
}

export enum JobApplicationStatus {
  SUBMITTED = "submitted",
  REVIEWED = "reviewed",
  INTERVIEW = "interview",
  ACCEPTED = "accepted",
  REJECTED = "rejected",
}

export enum Locale {
  EN = "en",
  NO = "no",
}

export enum ContentType {
  JOB = "job",
  EVENT = "event",
  NEWS = "news",
  PRODUCT = "product",
  DEPARTMENT = "department",
  MEMBER_BENEFIT = "memberBenefit",
  PAGE = "page",
}

export enum JobStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  CLOSED = "closed",
}

export enum EventStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  CANCELLED = "cancelled",
}

export enum CollectionPricing {
  BUNDLE = "bundle",
  INDIVIDUAL = "individual",
}

export enum EventCategory {
  SOCIAL = "social",
  CAREER = "career",
  WORKSHOP = "workshop",
  TALK = "talk",
  PARTY = "party",
  SPORT = "sport",
  ACADEMIC = "academic",
  TRIP = "trip",
}

export enum EventLocationMode {
  PHYSICAL = "physical",
  ONLINE = "online",
  HYBRID = "hybrid",
}

export enum EventCoverPattern {
  DOTTED = "dotted",
  LINEAR = "linear",
  CONCENTRIC = "concentric",
  WAVE = "wave",
  GRID = "grid",
  CUSTOM = "custom",
}

export enum EventPricingMode {
  FREE = "free",
  PAID = "paid",
}

export enum EventPublishMode {
  NOW = "now",
  SCHEDULED = "scheduled",
}

export enum NewsStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
}

export enum WebshopProductStatus {
  DRAFT = "draft",
  PENDING_APPROVAL = "pending_approval",
  PUBLISHED = "published",
  ARCHIVED = "archived",
}

export enum WebshopCoverPattern {
  DOTTED = "dotted",
  LINEAR = "linear",
  CONCENTRIC = "concentric",
  WAVE = "wave",
  GRID = "grid",
}

export enum WebshopInventoryMode {
  TRACKED = "tracked",
  UNLIMITED = "unlimited",
}

export enum Level {
  NATIONAL = "national",
  CAMPUS = "campus",
}

export enum PageStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  ARCHIVED = "archived",
}

export enum PageVisibility {
  PUBLIC = "public",
  AUTHENTICATED = "authenticated",
}

export enum PageLocale {
  NO = "no",
  EN = "en",
}

export enum BenefitLocale {
  EN = "en",
  NO = "no",
}

export enum CampusBenefitStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  ARCHIVED = "archived",
}

export enum CampusBenefitKind {
  OFFER = "offer",
  PERK = "perk",
  SERVICE = "service",
}

export enum RedemptionType {
  NONE = "none",
  CODE = "code",
  LINK = "link",
  QR = "qr",
  ONSITE = "onsite",
}

export enum Action {
  VIEW = "view",
  SAVE = "save",
  REVEAL = "reveal",
  CLICK = "click",
  REDEEM = "redeem",
}

export enum NavigationLocale {
  EN = "en",
  NO = "no",
}

export enum MentorStatus {
  PENDING = "pending",
  APPROVED = "approved",
  REJECTED = "rejected",
}

export enum ProfileVisibility {
  ALL_ALUMNI = "all_alumni",
  CONNECTIONS = "connections",
  LIMITED = "limited",
}

export enum MentoringProgramStatus {
  ACTIVE = "active",
  INACTIVE = "inactive",
}

export enum AlumniStatType {
  ALUMNI = "alumni",
  EVENTS = "events",
  MENTORSHIPS = "mentorships",
  JOBS = "jobs",
}

export type Users = Models.Row & {
  phone: string | null;
  address: string | null;
  city: string | null;
  zip: string | null;
  bank_account: string | null;
  name: string | null;
  email: string | null;
  campus: Campus;
  departments: Departments[];
  expenses: Expenses[];
  campus_id: string | null;
  department_ids: string[] | null;
  membership_ids: string[] | null;
  student_id: string | null;
  payments: Payments[];
  studentId: StudentIds;
  avatar: string | null;
  roles: string[] | null;
  isActive: boolean;
  swift: string | null;
  savedJobs: SavedJobs[];
  is_public: boolean | null;
  bio: string | null;
};

export type ExpenseAttachments = Models.Row & {
  date: string | null;
  url: string | null;
  amount: number | null;
  description: string | null;
  type: string;
};

export type Subscriptions = Models.Row & {
  user_id: string;
  topic: string;
  subscribed: boolean;
  subscriber_id: string;
};

export type Notifications = Models.Row & {
  status: NotificationStatus;
};

export type Expenses = Models.Row & {
  campus: string;
  department: string;
  bank_account: string;
  description: string | null;
  expenseAttachments: ExpenseAttachments[];
  total: number;
  prepayment_amount: number | null;
  status: ExpenseStatus;
  invoice_id: number | null;
  user: Users;
  userId: string;
  eventName: string | null;
  departmentRel: Departments;
  campusRel: Campus;
};

export type TwentyFourSevenOfficeAuthTokens = Models.Row & {
  token: string;
};

export type Departments = Models.Row & {
  Id: string;
  Name: string;
  campus: Campus;
  users: Users[];
  campus_id: string;
  logo: string | null;
  active: boolean | null;
  type: string | null;
  socials: DepartmentSocials[];
  news: News[];
  jobs: Jobs[];
  boardMembers: DepartmentBoard[];
  products: WebshopProducts[];
  translations: ContentTranslations[];
  hero: string | null;
  events: Events[];
};

export type StudentIds = Models.Row & {
  student_id: string;
  expiry_date: string | null;
  isMember: boolean;
  memberships: Memberships[];
  membership_ids: string[] | null;
  user: Users;
};

export type Campus = Models.Row & {
  name: string;
  departments: Departments[];
  users: Users[];
  savedJobs: SavedJobs[];
  campusData: CampusData;
  jobs: Jobs[];
  events: Events[];
  news: News[];
  webshop_products: WebshopProducts[];
  partners: Partners[];
  pages: Pages[];
  expenses: Expenses[];
  email: string | null;
};

export type Orders = Models.Row & {
  status: OrderStatus | null;
  userId: string | null;
  buyer_name: string | null;
  buyer_email: string | null;
  buyer_phone: string | null;
  subtotal: number;
  discount_total: number | null;
  total: number;
  currency: Currency;
  items_json: string | null;
  membership_applied: boolean | null;
  member_discount_percent: number | null;
  payment_provider: string | null;
  payment_session_id: string | null;
  payment_intent_id: string | null;
  receipt_link: string | null;
  payment_link: string | null;
  payment_receipt_url: string | null;
  campus_id: string | null;
  finago_transaction_id: string | null;
};

export type Memberships = Models.Row & {
  membership_id: string;
  studentId: StudentIds[];
  name: string;
  payments: Payments[];
  price: number;
  category: string | null;
  status: boolean;
  expiryDate: string;
  canPurchase: boolean;
  startDate: string;
};

export type Payments = Models.Row & {
  reference: string;
  amount: number;
  description: string | null;
  membership_id: string | null;
  membership: Memberships;
  status: string | null;
  paid_amount: number | null;
  user: Users;
  payment_method: string | null;
  user_id: string | null;
};

export type FollowedUnits = Models.Row & {
  user_id: string;
  department_ids: string[] | null;
};

export type BugReports = Models.Row & {
  description: string | null;
  user_id: string;
  user: Users;
  images: string[] | null;
};

export type SavedJobs = Models.Row & {
  jobId: number;
  title: string;
  campus: Campus[];
  user: Users[];
};

export type CampusData = Models.Row & {
  description: string | null;
  businessBenefits: string[] | null;
  studentBenefits: string[] | null;
  careerAdvantages: string[] | null;
  socialNetwork: string[] | null;
  safety: string[] | null;
  location: string | null;
  departmentBoard: DepartmentBoard[];
  name: string | null;
  name_en: string | null;
  name_nb: string | null;
  description_en: string | null;
  tagline_nb: string | null;
  tagline_en: string | null;
  highlights_nb: string[] | null;
  highlights_en: string[] | null;
  focusAreas_nb: string[] | null;
  focusAreas_en: string[] | null;
  services_nb: string | null;
  studentBenefits_nb: string[] | null;
  studentBenefits_en: string[] | null;
  careerAdvantages_nb: string[] | null;
  careerAdvantages_en: string[] | null;
  socialNetwork_nb: string[] | null;
  socialNetwork_en: string[] | null;
  safety_nb: string[] | null;
  safety_en: string[] | null;
  businessBenefits_nb: string[] | null;
  businessBenefits_en: string[] | null;
  description_nb: string | null;
};

export type DepartmentBoard = Models.Row & {
  name: string | null;
  imageUrl: string | null;
  role: string | null;
  department: Departments;
};

export type DepartmentSocials = Models.Row & {
  platform: string | null;
  url: string | null;
  department_id: string;
};

export type FeatureFlags = Models.Row & {
  key: string;
  enabled: boolean;
  description: string | null;
  title: string;
};

export type AppNotices = Models.Row & {
  title: string;
  description: string;
  color: string | null;
  actionUrl: string | null;
  actionLabel: string | null;
  priority: number;
  isActive: boolean;
  locale: AppNoticeLocale;
};

export type LargeEvent = Models.Row & {
  slug: string;
  name: string;
  description: string;
  startDate: string;
  endDate: string;
  isActive: boolean;
  heroOverrideEnabled: boolean;
  priority: number;
  primaryColorHex: string | null;
  secondaryColorHex: string | null;
  textColorHex: string | null;
  gradientHex: string[] | null;
  logoUrl: string | null;
  backgroundImageUrl: string | null;
  campusConfigs: string | null;
  showcaseType: string;
  contentMetadata: string | null;
  externalUrl: string | null;
  ctaText: string | null;
};

export type LargeEventItem = Models.Row & {
  eventId: LargeEvent;
  campusId: string;
  title: string;
  subtitle: string | null;
  startTime: string;
  endTime: string | null;
  coverImageUrl: string | null;
  location: string | null;
  ticketUrl: string | null;
  sort: number | null;
};

export type Products = Models.Row & {
  name: string;
  description: string;
  price: number;
  currency: string;
  seller_id: string;
  seller_name: string;
  seller_avatar: string | null;
  campus_id: string;
  category: string;
  images: string[] | null;
  condition: Condition;
  status: MarketplaceProductStatus;
  is_negotiable: boolean;
  contact_method: ContactMethod | null;
  contact_info: string | null;
  view_count: number;
  favorite_count: number;
  image_file_ids: string[] | null;
  favorites: ProductFavorites[];
};

export type ProductFavorites = Models.Row & {
  user_id: string;
  product: Products;
};

export type Chats = Models.Row & {
  name: string;
  description: string | null;
  type: ChatType;
  participants: string[];
  team_id: string | null;
  department_id: string | null;
  is_active: boolean;
  is_muted: boolean;
  unread_count: number;
  last_activity_at: string | null;
};

export type ChatMessages = Models.Row & {
  chat_id: string;
  sender_id: string;
  sender_name: string;
  content: string;
  type: ChatMessageType;
  attachments: string[] | null;
  is_edited: boolean;
  is_deleted: boolean;
  reply_to_id: string | null;
};

export type TypingIndicators = Models.Row & {
  chat_id: string;
  user_id: string;
  user_name: string;
  is_typing: boolean;
  expires_at: string;
};

export type Teams = Models.Row & {
  name: string;
  total: number;
  members: string[];
};

export type PublicProfiles = Models.Row & {
  user_id: string;
  name: string;
  email: string | null;
  phone: string | null;
  campus_id: string | null;
  avatar: string | null;
  email_visible: boolean;
  phone_visible: boolean;
};

export type CampusDataTranslations = Models.Row & {
  entry_id: string;
  locale: string;
  name: string | null;
  description: string | null;
  location: string | null;
  studentBenefits: string[] | null;
  careerAdvantages: string[] | null;
  socialNetwork: string[] | null;
  safety: string[] | null;
  businessBenefits: string[] | null;
  data: string | null;
};

export type CampusMetadata = Models.Row & {
  campus_id: string;
  campus_name: string;
  tagline_nb: string | null;
  tagline_en: string | null;
  description_nb: string | null;
  description_en: string | null;
  highlights_nb: string[] | null;
  highlights_en: string[] | null;
  focusAreas_nb: string[] | null;
  focusAreas_en: string[] | null;
  services_nb: string | null;
  services_en: string | null;
};

export type JobApplications = Models.Row & {
  job_id: string;
  applicant_name: string;
  applicant_email: string;
  applicant_phone: string | null;
  cover_letter: string | null;
  status: JobApplicationStatus;
  gdpr_consent: boolean;
  consent_date: string;
  data_processing_purpose: string;
  data_retention_until: string;
  resume_file_id: string | null;
  review_metadata: string | null;
};

export type ContentTranslations = Models.Row & {
  content_id: string;
  locale: Locale;
  title: string;
  description: string;
  additional_fields: string | null;
  job_ref: Jobs;
  event_ref: Events;
  news_ref: News;
  product_ref: WebshopProducts;
  content_type: ContentType;
  short_description: string | null;
  department_ref: Departments;
  memberBenefit: CampusBenefits;
};

export type Jobs = Models.Row & {
  slug: string;
  status: JobStatus;
  campus_id: string;
  department_id: string | null;
  metadata: string | null;
  campus: Campus;
  translations: ContentTranslations[];
  translation_refs: ContentTranslations[];
  department: Departments;
};

export type Events = Models.Row & {
  slug: string | null;
  status: EventStatus;
  campus_id: string;
  metadata: string | null;
  campus: Campus;
  translation_refs: ContentTranslations[];
  start_date: string | null;
  end_date: string | null;
  image: string | null;
  ticket_url: string | null;
  price: number | null;
  member_only: boolean;
  collection_id: string | null;
  is_collection: boolean;
  collection_pricing: CollectionPricing;
  location: string | null;
  department_id: string | null;
  department: Departments;
  registration_deadline: string | null;
  location_mode: EventLocationMode;
  online_url: string | null;
  capacity: number;
  waitlist: boolean;
  cover_pattern: EventCoverPattern;
  pricing_mode: EventPricingMode;
  member_price: number | null;
  publish_mode: EventPublishMode;
  scheduled_publish_at: string | null;
  notify_push: boolean;
  tags: string[];
  category: EventCategory | null;
  contact_name: string | null;
  contact_role: string | null;
  contact_email: string | null;
};

export type News = Models.Row & {
  slug: string | null;
  status: NewsStatus;
  campus_id: string;
  department_id: string | null;
  sticky: boolean | null;
  campus: Campus;
  translation_refs: ContentTranslations[];
  url: string | null;
  image: string | null;
  department: Departments;
  metadata: string[] | null;
  author: string | null;
};

export type WebshopProducts = Models.Row & {
  slug: string;
  status: WebshopProductStatus;
  campus_id: string;
  metadata: string | null;
  campus: Campus;
  translation_refs: ContentTranslations[];
  departmentId: string | null;
  regular_price: number;
  member_price: number | null;
  member_only: boolean;
  category: string | null;
  image: string | null;
  stock: number | null;
  department: Departments;
  variants_json: string | null;
  tags: string[] | null;
  images: string[] | null;
  cover_pattern: WebshopCoverPattern | null;
  linked_event_id: string | null;
  inventory_mode: WebshopInventoryMode | null;
  finago_account_number: number | null;
};

export type VarslingSettings = Models.Row & {
  campus_id: string;
  role_name: string;
  email: string;
  sort_order: number;
  is_active: boolean;
};

export type Partners = Models.Row & {
  name: string;
  url: string | null;
  level: Level;
  campus: Campus;
  image_url: string;
  campus_id: string;
};

export type ShopSettings = Models.Row & {
  general: string | null;
};

export type FundingPrograms = Models.Row & {
  slug: string;
  status: string;
  hero_image_url: string | null;
  application_url: string | null;
  document_url: string | null;
  contact_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  metadata: string | null;
};

export type Pages = Models.Row & {
  slug: string | null;
  campus_id: string | null;
  campus: Campus;
  status: PageStatus;
  visibility: PageVisibility;
  department_id: string | null;
  translation_refs: PageTranslations[];
};

export type PageTranslations = Models.Row & {
  page_id: string;
  locale: PageLocale | null;
  title: string;
  description: string | null;
  puck_document: string | null;
  draft_document: string | null;
  is_published: boolean;
  published_at: string | null;
  page: Pages;
};

export type TaxCodes = Models.Row & {
  code: string;
  name: string;
  rate: number;
  active: boolean;
};

export type AuditLogs = Models.Row & {
  actor_id: string | null;
  actor_email: string | null;
  action: string;
  resource_id: string | null;
  resource_type: string | null;
  payload: string | null;
};

export type CartReservations = Models.Row & {
  product_id: string;
  user_id: string;
  quantity: number;
  expires_at: string;
};

export type PageViewEvents = Models.Row & {
  path: string;
  locale: string | null;
  referrer: string | null;
  user_agent: string | null;
  visitor_ip: string | null;
  user_id: string | null;
};

export type DashboardMetrics = Models.Row & {
  metric_type: string;
  metric_data: string;
  date_range: string;
  computed_at: string;
};

export type CampusBenefits = Models.Row & {
  campus_id: string;
  status: CampusBenefitStatus;
  kind: CampusBenefitKind;
  redemption_type: RedemptionType;
  category: string;
  partner_id: string | null;
  partner_name: string | null;
  partner_logo_url: string | null;
  title_nb: string;
  title_en: string;
  description_nb: string;
  description_en: string;
  teaser_nb: string | null;
  teaser_en: string | null;
  terms_nb: string | null;
  terms_en: string | null;
  redemption_value: string | null;
  image_url: string | null;
  is_featured: boolean;
  is_member_only: boolean;
  publish_start: string | null;
  publish_end: string | null;
  sort_order: number;
  created_by: string | null;
  updated_by: string | null;
};

export type BenefitPartners = Models.Row & {
  name: string;
  website_url: string | null;
  logo_url: string | null;
  description_nb: string | null;
  description_en: string | null;
  campus_id: string | null;
  is_active: boolean;
};

export type BenefitReveals = Models.Row & {
  user_id: string;
  benefit_id: string;
  revealed_at: string;
};

export type BenefitInteractions = Models.Row & {
  user_id: string | null;
  benefit_id: string;
  action: Action;
  campus_id: string | null;
  metadata: string | null;
};

export type LegacyDepartments = Models.Row & {
  Id: string;
  Name: string;
  Campus: string | null;
};

export type AuthTokens = Models.Row & {
  token: string;
};

export type DashboardCustomization = Models.Row & {
  userId: string;
  layout: string;
  groups: string | null;
};

export type LegacyCampusDataTranslations = Models.Row & {
  entry_id: string;
  locale: string;
  name: string | null;
  description: string | null;
  location: string | null;
  studentBenefits: string[] | null;
  careerAdvantages: string[] | null;
  socialNetwork: string[] | null;
  safety: string[] | null;
  businessBenefits: string[] | null;
};

export type NavigationMenu = Models.Row & {
  slug: string;
  parent_id: string | null;
  path: string | null;
  url: string | null;
  order: number | null;
  is_external: boolean | null;
  translation_refs: NavigationMenuTranslations[];
};

export type NavigationMenuTranslations = Models.Row & {
  nav_id: string;
  locale: NavigationLocale;
  title: string;
  nav_ref: NavigationMenu;
};

export type AlumniEvents = Models.Row & {
  title: string;
  description: string;
  category: string;
  date: string;
  endDate: string | null;
  location: string;
  attendees: number;
  maxAttendees: number;
  online: boolean;
  registrationRequired: boolean;
  featured: boolean;
  image: string | null;
  organizer: string;
  registrationDeadline: string | null;
};

export type AlumniJobs = Models.Row & {
  title: string;
  company: string;
  companyLogo: string | null;
  location: string;
  type: string;
  workMode: string;
  salary: string | null;
  experience: string;
  category: string;
  description: string;
  postedDate: string;
  applicationDeadline: string;
  featured: boolean;
  alumni: boolean;
  responsibilities: string[];
  qualifications: string[];
};

export type Mentors = Models.Row & {
  name: string;
  avatarUrl: string | null;
  title: string;
  company: string;
  expertise: string[];
  industry: string;
  experience: number;
  education: string;
  location: string;
  availability: string;
  rating: number;
  reviewCount: number;
  bio: string;
  featured: boolean;
  graduationYear: string;
  languages: string[] | null;
  menteeCount: number | null;
  maxMentees: number | null;
  industries: string[] | null;
  meetingPreference: string[] | null;
  userProfile: UserProfiles;
  userProfileId: string | null;
  status: MentorStatus;
};

export type UserProfiles = Models.Row & {
  name: string;
  avatarUrl: string | null;
  email: string;
  phone: string | null;
  location: string;
  title: string;
  company: string | null;
  graduationYear: string;
  department: string | null;
  degree: string | null;
  bio: string | null;
  skills: string[] | null;
  interests: string[] | null;
  profileCompletion: number | null;
  userId: string;
  available: boolean | null;
};

export type Experiences = Models.Row & {
  title: string;
  company: string;
  location: string | null;
  startDate: string;
  endDate: string | null;
  current: boolean;
  description: string | null;
  userId: string;
  userProfile: UserProfiles;
};

export type Education = Models.Row & {
  degree: string;
  institution: string;
  location: string | null;
  startYear: string;
  endYear: string;
  description: string | null;
  userId: string;
  userProfile: UserProfiles;
  fieldOfStudy: string | null;
};

export type Certifications = Models.Row & {
  name: string;
  issuer: string;
  issueDate: string;
  expiryDate: string | null;
  description: string | null;
  userId: string;
  userProfile: UserProfiles;
};

export type Conversations = Models.Row & {
  participants: string[];
  unreadCount: number;
  lastMessageId: string | null;
  lastMessage: Messages;
};

export type Messages = Models.Row & {
  content: string;
  sender: string;
  read: boolean;
  conversationId: string;
  conversation: Conversations;
};

export type Resources = Models.Row & {
  title: string;
  description: string;
  category: string;
  type: string;
  format: string;
  author: string;
  publishedDate: string;
  fileSize: string | null;
  duration: string | null;
  thumbnail: string | null;
  featured: boolean;
  downloadUrl: string | null;
  watchUrl: string | null;
  listenUrl: string | null;
  tags: string[] | null;
};

export type Languages = Models.Row & {
  language: string;
  proficiency: string;
  userId: string;
  userProfile: UserProfiles;
};

export type SocialLinks = Models.Row & {
  platform: string;
  url: string;
  userId: string;
  userProfile: UserProfiles;
};

export type PrivacySettings = Models.Row & {
  showEmail: boolean;
  showPhone: boolean;
  showSocial: boolean;
  allowMessages: boolean;
  allowMentoring: boolean;
  userId: string;
  userProfile: UserProfiles;
  profileVisibility: ProfileVisibility;
  showEducation: boolean;
  showWork: boolean;
  showLocation: boolean;
  allowConnections: boolean;
};

export type MentoringPrograms = Models.Row & {
  title: string;
  description: string;
  category: string;
  duration: string | null;
  commitment: string | null;
  startDate: string | null;
  applicationDeadline: string | null;
  spots: number | null;
  spotsRemaining: number | null;
  featured: boolean;
  image: string;
  status: MentoringProgramStatus;
};

export type Testimonials = Models.Row & {
  name: string | null;
  role: string | null;
  graduationYear: string | null;
  quote: string | null;
  avatarUrl: string | null;
  featured: boolean;
};

export type AlumniStatisticalHistory = Models.Row & {
  type: AlumniStatType;
  count: number;
  date: string;
  period: string;
};

export type AlumniNews = Models.Row & {
  title: string;
  summary: string;
  content: string;
  date: string;
  author: string;
  category: string;
  image: string;
  tags: string[] | null;
  featured: boolean;
  views: number | null;
};

export type StopPlaces = Models.Row & {
  stopPlaceId: string;
  name: string | null;
  enabled: boolean;
  campus_id: string;
};

export type Departures = Models.Row & {
  stopPlaceId: string;
  stopPlaceName: string | null;
  updatedAt: string;
  estimatedCalls: string | null;
};

export enum DocumentCategory {
  NATIONAL_STATUTES = "national-statutes",
  CAMPUS_BYLAWS = "campus-bylaws",
  CODE_OF_CONDUCT = "code-of-conduct",
  BUSINESS_REGULATIONS = "business-regulations",
  COMMUNICATION_GUIDELINES = "communication-guidelines",
  AUTHORIZATION_MATRIX = "authorization-matrix",
  TARGET_DOCUMENTS = "target-documents",
}

export enum DocumentScope {
  NATIONAL = "national",
  CAMPUS = "campus",
}

export enum DocumentStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
}

export type Documents = Models.Row & {
  title: string;
  description: string | null;
  category: DocumentCategory;
  scope: DocumentScope;
  campus_id: string | null;
  version: string | null;
  version_number: number;
  sharepoint_item_id: string;
  sharepoint_drive_id: string;
  sharepoint_web_url: string;
  file_size: number | null;
  status: DocumentStatus;
  sort_order: number;
  updated_by: string | null;
  language: string | null;
};
