import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language ts ./types`.

export enum NotificationStatus {
    READ = "read",
    UNREAD = "unread"
}

export enum ExpenseStatus {
    DRAFT = "draft",
    PENDING = "pending",
    SUCCESS = "success",
    SUBMITTED = "submitted",
    REJECTED = "rejected"
}

export enum OrderStatus {
    PENDING = "pending",
    AUTHORIZED = "authorized",
    PAID = "paid",
    CANCELLED = "cancelled",
    FAILED = "failed",
    REFUNDED = "refunded"
}

export enum Currency {
    NOK = "NOK"
}


export enum Condition {
    NEW = "new",
    LIKE_NEW = "like_new",
    GOOD = "good",
    FAIR = "fair",
    POOR = "poor"
}

export enum MarketPlaceProductStatus {
    AVAILABLE = "available",
    SOLD = "sold",
    RESERVED = "reserved",
    INACTIVE = "inactive"
}

export enum ContactMethod {
    MESSAGE = "message",
    PHONE = "phone",
    EMAIL = "email"
}

export enum Type {
    DIRECT = "direct",
    GROUP = "group",
    TEAM = "team",
    DEPARTMENT = "department"
}

export enum Type {
    TEXT = "text",
    IMAGE = "image",
    FILE = "file",
    SYSTEM = "system",
    PRODUCT = "product"
}

export enum JobApplicationStatus {
    SUBMITTED = "submitted",
    REVIEWED = "reviewed",
    INTERVIEW = "interview",
    ACCEPTED = "accepted",
    REJECTED = "rejected"
}

export enum Locale {
    EN = "en",
    NO = "no"
}

export enum ContentType {
    JOB = "job",
    EVENT = "event",
    NEWS = "news",
    PRODUCT = "product",
    DEPARTMENT = "department"
}

export enum Status {
    DRAFT = "draft",
    PUBLISHED = "published",
    CLOSED = "closed",
    ARCHIVED = "archived"
}


export enum PageStatus {
    DRAFT = "draft",
    PUBLISHED = "published",
    ARCHIVED = "archived"
}

export enum PageVisibility {
    PUBLIC = "public",
    AUTHENTICATED = "authenticated"
}


export enum Level {
    NATIONAL = "national",
    CAMPUS = "campus"
}

export type Users = Models.Row & {
    phone: string | null;
    address: string | null;
    city: string | null;
    zip: string | null;
    bank_account: string | null;
    name: string | null;
    email: string | null;
    campus: Campus;
    departments: Departments[];
    expenses: Expenses[];
    campus_id: string | null;
    department_ids: string[] | null;
    membership_ids: string[] | null;
    student_id: string | null;
    payments: Payments[];
    studentId: StudentIds;
    avatar: string | null;
    roles: string[] | null;
    isActive: boolean;
    swift: string | null;
    savedJobs: SavedJobs[];
    is_public: boolean | null;
}

export type ExpenseAttachments = Models.Row & {
    date: string | null;
    url: string | null;
    amount: number | null;
    description: string | null;
    type: string;
}

export type Subscriptions = Models.Row & {
    user_id: string;
    topic: string;
    subscribed: boolean;
    subscriber_id: string;
}

export type Notifications = Models.Row & {
    status: Status;
}

export type Expenses = Models.Row & {
    campus: string;
    department: string;
    bank_account: string;
    description: string | null;
    expenseAttachments: ExpenseAttachments[];
    total: number;
    prepayment_amount: number | null;
    status: ExpenseStatus;
    invoice_id: number | null;
    user: Users;
    userId: string;
    eventName: string | null;
    departmentRel: Departments;
}

export type TwentyFourSevenOfficeAuthTokens = Models.Row & {
    token: string;
}

export type Departments = Models.Row & {
    Id: string;
    Name: string;
    campus: Campus;
    users: Users[];
    campus_id: string;
    logo: string | null;
    active: boolean | null;
    type: string | null;
    socials: DepartmentSocials[];
    news: News[];
    boardMembers: DepartmentBoard[];
    products: WebshopProducts[];
    translations: ContentTranslations[];
    translation_refs: ContentTranslations[];
    hero: string | null;
    department_id: string | null;
    department: Departments;
}

export type DepartmentSocials = Models.Row & {
    platform: string | null;
    url: string | null;
    department_id: string;
}


export type StudentIds = Models.Row & {
    student_id: string;
    expiry_date: string | null;
    isMember: boolean;
    memberships: Memberships[];
    membership_ids: string[] | null;
    user: Users;
}

export type Campus = Models.Row & {
    name: string;
    departments: Departments[];
    users: Users[];
    savedJobs: SavedJobs[];
    campusData: CampusData;
    jobs: Jobs[];
    events: Events[];
    news: News[];
    webshop_products: WebshopProducts[];
    partners: Partners[];
}

export type Orders = Models.Row & {
    status: OrderStatus | null;
    userId: string | null;
    buyer_name: string | null;
    buyer_email: string | null;
    buyer_phone: string | null;
    subtotal: number;
    discount_total: number | null;
    total: number;
    currency: Currency;
    items_json: string | null;
    membership_applied: boolean | null;
    member_discount_percent: number | null;
    vipps_session_id: string | null;
    vipps_order_id: string | null;
    vipps_payment_link: string | null;
    vipps_receipt_url: string | null;
    campus_id: string | null;
}

export type CartReservations = Models.Row & {
    product_id: string;
    user_id: string;
    quantity: number;
    expires_at: string;
}

export type Memberships = Models.Row & {
    membership_id: string;
    studentId: StudentIds[];
    name: string;
    payments: Payments[];
    price: number;
    category: string | null;
    status: boolean;
    expiryDate: string;
    canPurchase: boolean;
}

export type Payments = Models.Row & {
    reference: string;
    amount: number;
    description: string | null;
    membership_id: string | null;
    membership: Memberships;
    status: string | null;
    paid_amount: number | null;
    user: Users;
    payment_method: string | null;
    user_id: string | null;
}

export type FollowedUnits = Models.Row & {
    user_id: string;
    department_ids: string[] | null;
}

export type BugReports = Models.Row & {
    description: string | null;
    user_id: string;
    user: Users;
    images: string[] | null;
}

export type SavedJobs = Models.Row & {
    jobId: number;
    title: string;
    campus: Campus[];
    user: Users[];
}

export type CampusData = Models.Row & {
    description: string | null;
    businessBenefits: string[] | null;
    studentBenefits: string[] | null;
    careerAdvantages: string[] | null;
    socialNetwork: string[] | null;
    safety: string[] | null;
    location: string | null;
    departmentBoard: DepartmentBoard[];
    name: string | null;
    name_en: string | null;
    name_nb: string | null;
    description_en: string | null;
    tagline_nb: string | null;
    tagline_en: string | null;
    highlights_nb: string[] | null;
    highlights_en: string[] | null;
    focusAreas_nb: string[] | null;
    focusAreas_en: string[] | null;
    services_nb: string | null;
    studentBenefits_nb: string[] | null;
    studentBenefits_en: string[] | null;
    careerAdvantages_nb: string[] | null;
    careerAdvantages_en: string[] | null;
    socialNetwork_nb: string[] | null;
    socialNetwork_en: string[] | null;
    safety_nb: string[] | null;
    safety_en: string[] | null;
    businessBenefits_nb: string[] | null;
    businessBenefits_en: string[] | null;
    description_nb: string | null;
}

export type DepartmentBoard = Models.Row & {
    name: string | null;
    imageUrl: string | null;
    role: string | null;
    department: Departments;
}


export type FeatureFlags = Models.Row & {
    key: string;
    enabled: boolean;
    description: string | null;
    title: string;
}

export type AppNotices = Models.Row & {
    title: string;
    description: string;
    color: string | null;
    actionUrl: string | null;
    actionLabel: string | null;
    priority: number;
    isActive: boolean;
    locale: Locale;
}

export type PageViewEvents = Models.Row & {
    path: string;
    locale: Locale | string | null;
    referrer: string | null;
    user_agent: string | null;
    visitor_ip: string | null;
    user_id: string | null;
}

export type LargeEvent = Models.Row & {
    slug: string;
    name: string;
    description: string;
    startDate: string;
    endDate: string;
    isActive: boolean;
    heroOverrideEnabled: boolean;
    priority: number;
    primaryColorHex: string | null;
    secondaryColorHex: string | null;
    textColorHex: string | null;
    gradientHex: string[] | null;
    logoUrl: string | null;
    backgroundImageUrl: string | null;
    campusConfigs: string | null;
    showcaseType: string;
    contentMetadata: string | null;
    externalUrl: string | null;
    ctaText: string | null;
}

export type LargeEventItem = Models.Row & {
    eventId: LargeEvent;
    campusId: string;
    title: string;
    subtitle: string | null;
    startTime: string;
    endTime: string | null;
    coverImageUrl: string | null;
    location: string | null;
    ticketUrl: string | null;
    sort: number | null;
}

export type Products = Models.Row & {
    name: string;
    description: string;
    price: number;
    currency: string;
    seller_id: string;
    seller_name: string;
    seller_avatar: string | null;
    campus_id: string;
    category: string;
    images: string[] | null;
    condition: Condition;
    status: Status;
    is_negotiable: boolean;
    contact_method: ContactMethod | null;
    contact_info: string | null;
    view_count: number;
    favorite_count: number;
    image_file_ids: string[] | null;
    favorites: ProductFavorites[];
}

export type ProductFavorites = Models.Row & {
    user_id: string;
    product: Products;
}

export type Chats = Models.Row & {
    name: string;
    description: string | null;
    type: Type;
    participants: string[];
    team_id: string | null;
    department_id: string | null;
    is_active: boolean;
    is_muted: boolean;
    unread_count: number;
    last_activity_at: string | null;
}

export type ChatMessages = Models.Row & {
    chat_id: string;
    sender_id: string;
    sender_name: string;
    content: string;
    type: Type;
    attachments: string[] | null;
    is_edited: boolean;
    is_deleted: boolean;
    reply_to_id: string | null;
}

export type TypingIndicators = Models.Row & {
    chat_id: string;
    user_id: string;
    user_name: string;
    is_typing: boolean;
    expires_at: string;
}

export type Teams = Models.Row & {
    name: string;
    total: number;
    members: string[];
}

export type PublicProfiles = Models.Row & {
    user_id: string;
    name: string;
    email: string | null;
    phone: string | null;
    campus_id: string | null;
    avatar: string | null;
    email_visible: boolean;
    phone_visible: boolean;
}

export type CampusDataTranslations = Models.Row & {
    entry_id: string;
    locale: string;
    name: string | null;
    description: string | null;
    location: string | null;
    studentBenefits: string[] | null;
    careerAdvantages: string[] | null;
    socialNetwork: string[] | null;
    safety: string[] | null;
    businessBenefits: string[] | null;
    data: string | null;
}

export type CampusMetadata = Models.Row & {
    campus_id: string;
    campus_name: string;
    tagline_nb: string | null;
    tagline_en: string | null;
    description_nb: string | null;
    description_en: string | null;
    highlights_nb: string[] | null;
    highlights_en: string[] | null;
    focusAreas_nb: string[] | null;
    focusAreas_en: string[] | null;
    services_nb: string | null;
    services_en: string | null;
}

export type JobApplications = Models.Row & {
    job_id: string;
    applicant_name: string;
    applicant_email: string;
    applicant_phone: string | null;
    cover_letter: string | null;
    status: Status;
    gdpr_consent: boolean;
    consent_date: string;
    data_processing_purpose: string;
    data_retention_until: string;
    resume_file_id: string | null;
}

export type ContentTranslations = Models.Row & {
    content_id: string;
    locale: Locale;
    title: string;
    description: string;
    short_description: string | null;
    additional_fields: string | null;
    job_ref: Jobs;
    event_ref: Events;
    news_ref: News;
    product_ref: WebshopProducts;
    department_ref: Departments;
    content_type: ContentType;
}

export type Jobs = Models.Row & {
    slug: string;
    status: Status;
    campus_id: string;
    department: Departments;
    department_id: string | null;
    metadata: Record<string, any> | null;
    campus: Campus;
    translations: ContentTranslations[];
    translation_refs: ContentTranslations[];
}

export type Events = Models.Row & {
    slug: string | null;
    status: Status;
    campus_id: string;
    metadata: string | null;
    start_date: string | null;
    end_date: string | null;
    location: string | null;
    price: number | null;
    ticket_url: string | null;
    image: string | null;
    member_only: boolean;
    collection_id: string | null;
    is_collection: boolean;
    collection_pricing: 'bundle' | 'individual' | null;
    department_id: string | null;
    campus: Campus | string;
    department: Departments | string | null;
    translation_refs: ContentTranslations[] | string[];
}

export type News = Models.Row & {
    slug: string | null;
    status: Status;
    campus_id: string;
    department_id: string | null;
    sticky: boolean | null;
    campus: Campus;
    translation_refs: ContentTranslations[];
    url: string | null;
    image: string | null;
    department: Departments;
    metadata: string[] | null;
    author?: string | null;
}

export type WebshopProducts = Models.Row & {
    slug: string;
    status: Status;
    campus_id: string;
    category: string;
    regular_price: number;
    member_price: number | null;
    member_only: boolean;
    image: string | null;
    stock: number | null;
    metadata: string | null;
    campus: Campus;
    translation_refs: ContentTranslations[];
    departmentId: string | null;
    department: Departments;
}

export type VarslingSettings = Models.Row & {
    campus_id: string;
    role_name: string;
    email: string;
    sort_order: number;
    is_active: boolean;
}

export type Partners = Models.Row & {
    name: string;
    url: string | null;
    level: Level;
    campus: Campus;
    image_url: string;
    campus_id: string;
}

export type ShopSettings = Models.Row & {
    general: string | null;
}

export type FundingPrograms = Models.Row & {
    slug: string;
    status: string;
    hero_image_url: string | null;
    application_url: string | null;
    document_url: string | null;
    contact_name: string | null;
    contact_email: string | null;
    contact_phone: string | null;
    metadata: string | null;
}

export type Pages = Models.Row & {
    slug: string;
    title: string;
    status: PageStatus;
    visibility: PageVisibility;
    template: string | null;
    campus_id: string | null;
    campus: Campus;
    translation_refs: PageTranslations[];
}

export type PageTranslations = Models.Row & {
    page_id: string;
    page: Pages;
    locale: Locale;
    title: string;
    slug: string | null;
    description: string | null;
    puck_document: string | null;
    draft_document: string | null;
    is_published: boolean;
    published_at: string | null;
}

export type SitePages = Models.Row & {
    slug: string;
    status: string | null;
    translation_refs: ContentTranslations;
}

export type TaxCodes = Models.Row & {
    code: string;
    name: string;
    rate: number;
    active: boolean;
}

export type AuditLogs = Models.Row & {
    actor_id: string | null;
    actor_email: string | null;
    action: string;
    resource_id: string | null;
    resource_type: string | null;
    payload: string | null;
}
