import type { Models } from "appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts ./types`.

export enum OrdersStatus {
  PENDING = "pending",
  AUTHORIZED = "authorized",
  PAID = "paid",
  CANCELLED = "cancelled",
  FAILED = "failed",
  REFUNDED = "refunded",
}

export enum OrdersCurrency {
  NOK = "NOK",
}

export enum EventsStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  CANCELLED = "cancelled",
}

export enum EventsCollectionPricing {
  BUNDLE = "bundle",
  INDIVIDUAL = "individual",
}

export enum EventsLocationMode {
  PHYSICAL = "physical",
  ONLINE = "online",
  HYBRID = "hybrid",
}

export enum EventsCoverPattern {
  DOTTED = "dotted",
  LINEAR = "linear",
  CONCENTRIC = "concentric",
  WAVE = "wave",
  GRID = "grid",
  CUSTOM = "custom",
}

export enum EventsPricingMode {
  FREE = "free",
  PAID = "paid",
}

export enum EventsPublishMode {
  NOW = "now",
  SCHEDULED = "scheduled",
}

export enum EventsCategory {
  SOCIAL = "social",
  CAREER = "career",
  WORKSHOP = "workshop",
  TALK = "talk",
  PARTY = "party",
  SPORT = "sport",
  ACADEMIC = "academic",
  TRIP = "trip",
}

export enum ExpensesStatus {
  DRAFT = "draft",
  PENDING = "pending",
  APPROVED = "approved",
  SUCCESS = "success",
  SUBMITTED = "submitted",
  REJECTED = "rejected",
  FAILED = "failed",
}

export enum JobsStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  CLOSED = "closed",
}

export enum PageViewEventsLocale {
  EN = "en",
  NO = "no",
}

export enum JobApplicationsStatus {
  SUBMITTED = "submitted",
  REVIEWED = "reviewed",
  INTERVIEW = "interview",
  ACCEPTED = "accepted",
  REJECTED = "rejected",
}

export enum JobApplicationsEmbeddingStatus {
  PENDING = "pending",
  READY = "ready",
  FAILED = "failed",
}

export enum WebshopProductsStatus {
  DRAFT = "draft",
  PENDING_APPROVAL = "pending_approval",
  PUBLISHED = "published",
  ARCHIVED = "archived",
}

export enum WebshopProductsCoverPattern {
  DOTTED = "dotted",
  LINEAR = "linear",
  CONCENTRIC = "concentric",
  WAVE = "wave",
  GRID = "grid",
}

export enum WebshopProductsInventoryMode {
  TRACKED = "tracked",
  UNLIMITED = "unlimited",
}

export enum ContentTranslationsLocale {
  EN = "en",
  NO = "no",
}

export enum ContentTranslationsContentType {
  JOB = "job",
  EVENT = "event",
  NEWS = "news",
  PRODUCT = "product",
  DEPARTMENT = "department",
  MEMBER_BENEFIT = "memberBenefit",
  PAGE = "page",
}

export enum AppNoticesLocale {
  NORWEGIAN = "norwegian",
  ENGLISH = "english",
}

export enum PartnersLevel {
  NATIONAL = "national",
  CAMPUS = "campus",
}

export enum NewsStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
}

export enum BenefitInteractionsAction {
  VIEW = "view",
  SAVE = "save",
  REVEAL = "reveal",
  CLICK = "click",
  REDEEM = "redeem",
}

export enum CampusBenefitsStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  ARCHIVED = "archived",
}

export enum CampusBenefitsKind {
  OFFER = "offer",
  PERK = "perk",
  SERVICE = "service",
}

export enum CampusBenefitsRedemptionType {
  NONE = "none",
  CODE = "code",
  LINK = "link",
  QR = "qr",
  ONSITE = "onsite",
}

export enum DocumentsCategory {
  NATIONAL_STATUTES = "national-statutes",
  CAMPUS_BYLAWS = "campus-bylaws",
  CODE_OF_CONDUCT = "code-of-conduct",
  BUSINESS_REGULATIONS = "business-regulations",
  COMMUNICATION_GUIDELINES = "communication-guidelines",
}

export enum DocumentsScope {
  NATIONAL = "national",
  CAMPUS = "campus",
}

export enum DocumentsStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
}

export enum DocumentsLanguage {
  NO = "no",
  EN = "en",
}

export enum ContentEntriesKind {
  PAGE = "page",
  POLICY = "policy",
  ARTICLE = "article",
}

export enum ContentEntriesStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  ARCHIVED = "archived",
}

export enum ContentEntriesVisibility {
  PUBLIC = "public",
  AUTHENTICATED = "authenticated",
}

export enum ContentEntriesScope {
  GLOBAL = "global",
  CAMPUS = "campus",
  DEPARTMENT = "department",
}

export enum ContentEntriesSourceLocale {
  NO = "no",
  EN = "en",
}

export enum ContentTemplatesFamily {
  PAGE = "page",
  POLICY = "policy",
  ARTICLE = "article",
}

export enum PageTranslationsLocale {
  NO = "no",
  EN = "en",
}

export enum ContentEntryLocalesLocale {
  NO = "no",
  EN = "en",
}

export enum ContentEntryLocalesTranslationStatus {
  SOURCE = "source",
  MANUAL = "manual",
  AI = "ai",
  STALE = "stale",
}

export enum ContentEntryLocalesTranslatedFromLocale {
  NO = "no",
  EN = "en",
}

export enum NotificationsStatus {
  READ = "read",
  UNREAD = "unread",
}

export enum TourProgressStatus {
  NOT_STARTED = "not_started",
  IN_PROGRESS = "in_progress",
  COMPLETED = "completed",
  DISMISSED = "dismissed",
}

export enum ChatsType {
  DIRECT = "direct",
  GROUP = "group",
  TEAM = "team",
  DEPARTMENT = "department",
}

export enum ChatMessagesType {
  TEXT = "text",
  IMAGE = "image",
  FILE = "file",
  SYSTEM = "system",
  PRODUCT = "product",
}

export enum ProductsCondition {
  NEW = "new",
  LIKE_NEW = "like_new",
  GOOD = "good",
  FAIR = "fair",
  POOR = "poor",
}

export enum ProductsStatus {
  AVAILABLE = "available",
  SOLD = "sold",
  RESERVED = "reserved",
  INACTIVE = "inactive",
}

export enum ProductsContactMethod {
  MESSAGE = "message",
  PHONE = "phone",
  EMAIL = "email",
}

export enum ContentTemplateVersionsStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
}

export enum PagesStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  ARCHIVED = "archived",
}

export enum PagesVisibility {
  PUBLIC = "public",
  AUTHENTICATED = "authenticated",
}

export enum FormSubmissionsStatus {
  NEW = "new",
  READ = "read",
  ACTIONED = "actioned",
  ARCHIVED = "archived",
}

export enum FormSubmissionsSource {
  MULTI_STEP_FORM = "multiStepForm",
  SIGNUP = "signup",
}

export enum JobApplicationAnswersAnswerType {
  TEXT = "text",
  LONG_TEXT = "long_text",
  SELECT = "select",
  MULTI_SELECT = "multi_select",
  BOOLEAN = "boolean",
  NUMBER = "number",
}

export enum JobInterviewsStatus {
  PROPOSED = "proposed",
  SCHEDULED = "scheduled",
  COMPLETED = "completed",
  CANCELLED = "cancelled",
  NO_SHOW = "no_show",
}

export enum JobInterviewParticipantsRole {
  INTERVIEWER = "interviewer",
  CANDIDATE = "candidate",
  OBSERVER = "observer",
}

export enum JobInterviewParticipantsResponseStatus {
  PENDING = "pending",
  ACCEPTED = "accepted",
  TENTATIVE = "tentative",
  DECLINED = "declined",
}

export enum CandidateProfilesEmbeddingStatus {
  PENDING = "pending",
  READY = "ready",
  FAILED = "failed",
}

export enum JobInterviewScorecardsRecommendation {
  STRONG_HIRE = "strong_hire",
  HIRE = "hire",
  NO_HIRE = "no_hire",
  STRONG_NO_HIRE = "strong_no_hire",
  NEED_MORE_INFO = "need_more_info",
}

export enum ApprovalRequestsStatus {
  PENDING = "pending",
  APPROVED = "approved",
  REJECTED = "rejected",
  CANCELLED = "cancelled",
}

export enum AnnouncementsStatus {
  DRAFT = "draft",
  SCHEDULED = "scheduled",
  SENT = "sent",
  FAILED = "failed",
}

export enum AnnouncementsAudienceType {
  TOPIC = "topic",
  USERS = "users",
  SEGMENT = "segment",
  BROADCAST = "broadcast",
}

export enum M365TurnoverJobsStatus {
  RETENTION_ACTIVE = "retention_active",
  COMPLETED = "completed",
  RETENTION_START_FAILED = "retention_start_failed",
  STOP_FAILED = "stop_failed",
}

export enum PaymentSettingsProvider {
  VIPPS = "vipps",
  STRIPE = "stripe",
}

export enum ExpenseApprovalsApproverRole {
  FINANCE = "finance",
  MANAGER = "manager",
  DEPUTY = "deputy",
  CONTROLLER = "controller",
  NATIONAL = "national",
}

export enum ExpenseApprovalsStatus {
  PENDING = "pending",
  APPROVED = "approved",
  REJECTED = "rejected",
}

export enum ExpenseApprovalIssuesStatus {
  OPEN = "open",
  RESOLVED = "resolved",
}

export type Orders = Models.Row & {
  status: OrdersStatus | null;
  userId: string | null;
  buyer_name: string | null;
  buyer_email: string | null;
  buyer_phone: string | null;
  subtotal: number;
  discount_total: number | null;
  total: number;
  currency: OrdersCurrency;
  items_json: string | null;
  membership_applied: boolean | null;
  member_discount_percent: number | null;
  campus_id: string | null;
  payment_provider: string | null;
  payment_intent_id: string | null;
  payment_receipt_url: string | null;
  receipt_link: string | null;
  payment_session_id: string | null;
  payment_link: string | null;
  finago_transaction_id: string | null;
  transition_lock: number;
  finago_posting_lock: number;
};

export type DepartmentBoard = Models.Row & {
  department: Departments;
  name: string | null;
  imageUrl: string | null;
  role: string | null;
};

export type Events = Models.Row & {
  slug: string | null;
  status: EventsStatus;
  campus_id: string;
  metadata: string | null;
  campus: Campus;
  translation_refs: ContentTranslations[];
  start_date: string | null;
  end_date: string | null;
  image: string | null;
  ticket_url: string | null;
  price: number | null;
  member_only: boolean;
  collection_id: string | null;
  is_collection: boolean;
  collection_pricing: EventsCollectionPricing;
  location: string | null;
  department: Departments;
  department_id: string | null;
  registration_deadline: string | null;
  location_mode: EventsLocationMode;
  online_url: string | null;
  capacity: number;
  waitlist: boolean;
  cover_pattern: EventsCoverPattern;
  pricing_mode: EventsPricingMode;
  member_price: number | null;
  publish_mode: EventsPublishMode;
  scheduled_publish_at: string | null;
  notify_push: boolean;
  tags: string[] | null;
  category: EventsCategory | null;
  contact_name: string | null;
  contact_role: string | null;
  contact_email: string | null;
  external_source: string | null;
  external_id: string | null;
};

export type Expenses = Models.Row & {
  user: Users;
  campus: string;
  department: string;
  bank_account: string;
  description: string | null;
  expenseAttachments: ExpenseAttachments[];
  total: number;
  prepayment_amount: number | null;
  status: ExpensesStatus;
  invoice_id: number | null;
  userId: string;
  eventName: string | null;
  departmentRel: Departments;
  campusRel: Campus;
  ledger_transaction_id: string | null;
  submitter_is_financial_manager: boolean;
  posting_lock: number;
};

export type ExpenseAttachments = Models.Row & {
  date: string | null;
  url: string | null;
  amount: number | null;
  description: string | null;
  type: string;
  cost_type: string | null;
  account_number: number | null;
  tax_code: number | null;
  sort_order: number;
};

export type Jobs = Models.Row & {
  slug: string;
  status: JobsStatus;
  campus_id: string;
  department_id: string | null;
  metadata: string | null;
  campus: Campus;
  translations: ContentTranslations[];
  department: Departments;
  interview_template: string | null;
  custom_questions: string | null;
  screening_rubric: string | null;
  auto_screen: boolean;
  embedding_id: string | null;
  applications: JobApplications[];
  application_deadline: string | null;
};

export type Departments = Models.Row & {
  users: Users[];
  Id: string;
  Name: string;
  campus_id: string;
  logo: string | null;
  active: boolean | null;
  type: string | null;
  socials: DepartmentSocials[];
  boardMembers: DepartmentBoard[];
  products: WebshopProducts[];
  translations: ContentTranslations[];
  hero: string | null;
  campus: Campus;
  jobs: Jobs[];
  events: Events[];
  news: News[];
  abbreviation: string | null;
};

export type PageViewEvents = Models.Row & {
  path: string;
  locale: PageViewEventsLocale | null;
  referrer: string | null;
  user_agent: string | null;
  visitor_ip: string | null;
  user_id: string | null;
};

export type LargeEvent = Models.Row & {
  slug: string;
  name: string;
  description: string;
  startDate: string;
  endDate: string;
  isActive: boolean;
  priority: number;
  primaryColorHex: string | null;
  secondaryColorHex: string | null;
  gradientHex: string[] | null;
  campusConfigs: string | null;
  showcaseType: string;
  contentMetadata: string | null;
  externalUrl: string | null;
  heroOverrideEnabled: boolean;
  textColorHex: string | null;
  logoUrl: string | null;
  backgroundImageUrl: string | null;
  ctaText: string | null;
};

export type CampusData = Models.Row & {
  description: string | null;
  businessBenefits: string[] | null;
  studentBenefits: string[] | null;
  careerAdvantages: string[] | null;
  socialNetwork: string[] | null;
  safety: string[] | null;
  location: string | null;
  departmentBoard: DepartmentBoard[];
  name: string | null;
  name_en: string | null;
  name_nb: string | null;
  description_en: string | null;
  tagline_nb: string | null;
  tagline_en: string | null;
  highlights_nb: string[] | null;
  highlights_en: string[] | null;
  focusAreas_nb: string[] | null;
  focusAreas_en: string[] | null;
  studentBenefits_nb: string[] | null;
  studentBenefits_en: string[] | null;
  careerAdvantages_nb: string[] | null;
  careerAdvantages_en: string[] | null;
  socialNetwork_nb: string[] | null;
  socialNetwork_en: string[] | null;
  safety_nb: string[] | null;
  safety_en: string[] | null;
  businessBenefits_nb: string[] | null;
  businessBenefits_en: string[] | null;
  description_nb: string | null;
  services_nb: string | null;
};

export type CartReservations = Models.Row & {
  product_id: string;
  user_id: string;
  quantity: number;
  expires_at: string;
};

export type Users = Models.Row & {
  phone: string | null;
  address: string | null;
  city: string | null;
  zip: string | null;
  bank_account: string | null;
  name: string | null;
  email: string | null;
  departments: Departments[];
  expenses: Expenses[];
  campus_id: string | null;
  department_ids: string[] | null;
  student_id: string | null;
  avatar: string | null;
  roles: string[] | null;
  isActive: boolean;
  swift: string | null;
  bio: string | null;
  campus: Campus;
  payments: Payments[];
  membership_ids: string[] | null;
  studentId: StudentIds;
  is_public: boolean | null;
  savedJobs: SavedJobs[];
};

export type JobApplications = Models.Row & {
  job_id: string;
  applicant_name: string;
  applicant_email: string;
  applicant_phone: string | null;
  status: JobApplicationsStatus;
  gdpr_consent: boolean;
  consent_date: string;
  data_processing_purpose: string;
  data_retention_until: string;
  resume_file_id: string | null;
  cover_letter: string | null;
  review_metadata: string | null;
  candidate_profile_id: string | null;
  ai_screening: string | null;
  screening_score: number | null;
  embedding_status: JobApplicationsEmbeddingStatus;
  source: string | null;
  job: Jobs;
  candidate_profile: CandidateProfiles;
  interviews: JobInterviews[];
  answers: JobApplicationAnswers[];
};

export type Memberships = Models.Row & {
  membership_id: string;
  name: string;
  price: number;
  category: string | null;
  status: boolean;
  expiryDate: string;
  canPurchase: boolean;
  startDate: string;
  payments: Payments[];
  studentId: StudentIds[];
};

export type Campus = Models.Row & {
  expenses: Expenses[];
  name: string;
  departments: Departments[];
  users: Users[];
  campusData: CampusData;
  email: string | null;
  jobs: Jobs[];
  events: Events[];
  news: News[];
  webshop_products: WebshopProducts[];
  partners: Partners[];
  pages: Pages[];
  savedJobs: SavedJobs[];
};

export type WebshopProducts = Models.Row & {
  department: Departments;
  slug: string;
  status: WebshopProductsStatus;
  campus_id: string;
  metadata: string | null;
  campus: Campus;
  translation_refs: ContentTranslations[];
  departmentId: string | null;
  regular_price: number;
  member_price: number | null;
  member_only: boolean;
  category: string | null;
  image: string | null;
  stock: number | null;
  variants_json: string | null;
  tags: string[] | null;
  images: string[] | null;
  cover_pattern: WebshopProductsCoverPattern;
  linked_event_id: string | null;
  inventory_mode: WebshopProductsInventoryMode;
  finago_account_number: number | null;
};

export type VarslingSettings = Models.Row & {
  campus_id: string;
  role_name: string;
  email: string;
  sort_order: number;
  is_active: boolean;
};

export type ContentTranslations = Models.Row & {
  department_ref: Departments;
  content_id: string;
  locale: ContentTranslationsLocale;
  title: string;
  description: string;
  additional_fields: string | null;
  content_type: ContentTranslationsContentType;
  short_description: string | null;
  event_ref: Events;
  news_ref: News;
  product_ref: WebshopProducts;
  memberBenefit: CampusBenefits;
};

export type AppNotices = Models.Row & {
  title: string;
  description: string;
  color: string | null;
  actionUrl: string | null;
  actionLabel: string | null;
  priority: number;
  isActive: boolean;
  locale: AppNoticesLocale;
};

export type LargeEventItem = Models.Row & {
  eventId: LargeEvent;
  campusId: string;
  title: string;
  subtitle: string | null;
  startTime: string;
  endTime: string | null;
  coverImageUrl: string | null;
  location: string | null;
  ticketUrl: string | null;
  sort: number | null;
};

export type Partners = Models.Row & {
  name: string;
  url: string | null;
  level: PartnersLevel;
  campus: Campus;
  image_url: string;
  campus_id: string;
};

export type PublicProfiles = Models.Row & {
  user_id: string;
  name: string;
  email: string | null;
  phone: string | null;
  campus_id: string | null;
  avatar: string | null;
  email_visible: boolean;
  phone_visible: boolean;
};

export type DepartmentSocials = Models.Row & {
  platform: string | null;
  url: string | null;
  department_id: string;
};

export type BenefitReveals = Models.Row & {
  revealed_at: string;
  user_id: string;
  benefit_id: string;
};

export type AuditLogs = Models.Row & {
  actor_id: string | null;
  actor_email: string | null;
  action: string;
  resource_id: string | null;
  resource_type: string | null;
  payload: string | null;
};

export type News = Models.Row & {
  slug: string | null;
  status: NewsStatus;
  campus_id: string;
  department_id: string | null;
  sticky: boolean | null;
  campus: Campus;
  translation_refs: ContentTranslations[];
  url: string | null;
  image: string | null;
  department: Departments;
  metadata: string[] | null;
  author: string | null;
};

export type CampusMetadata = Models.Row & {
  campus_id: string;
  campus_name: string;
  tagline_nb: string | null;
  tagline_en: string | null;
  description_nb: string | null;
  description_en: string | null;
  highlights_nb: string[] | null;
  highlights_en: string[] | null;
  focusAreas_nb: string[] | null;
  focusAreas_en: string[] | null;
  services_nb: string | null;
  services_en: string | null;
};

export type FundingPrograms = Models.Row & {
  slug: string;
  status: string;
  hero_image_url: string | null;
  application_url: string | null;
  document_url: string | null;
  contact_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  metadata: string | null;
};

export type BenefitInteractions = Models.Row & {
  user_id: string | null;
  benefit_id: string;
  action: BenefitInteractionsAction;
  campus_id: string | null;
  metadata: string | null;
};

export type CampusBenefits = Models.Row & {
  campus_id: string;
  status: CampusBenefitsStatus;
  kind: CampusBenefitsKind;
  redemption_type: CampusBenefitsRedemptionType;
  category: string;
  partner_name: string | null;
  partner_logo_url: string | null;
  title_nb: string;
  title_en: string;
  description_nb: string;
  description_en: string;
  teaser_nb: string | null;
  teaser_en: string | null;
  terms_en: string | null;
  redemption_value: string | null;
  image_url: string | null;
  is_featured: boolean;
  is_member_only: boolean;
  publish_start: string | null;
  publish_end: string | null;
  sort_order: number;
  updated_by: string | null;
  contentTranslations: ContentTranslations[];
  partner_id: string | null;
  terms_nb: string | null;
  created_by: string | null;
};

export type Documents = Models.Row & {
  title: string;
  description: string | null;
  category: DocumentsCategory;
  scope: DocumentsScope;
  campus_id: string | null;
  version: string | null;
  version_number: number;
  sharepoint_item_id: string;
  sharepoint_drive_id: string;
  sharepoint_web_url: string;
  file_size: number | null;
  status: DocumentsStatus;
  sort_order: number;
  updated_by: string | null;
  language: DocumentsLanguage | null;
};

export type Subscriptions = Models.Row & {
  user_id: string;
  topic: string;
  subscribed: boolean;
  subscriber_id: string;
};

export type TwentyFourSevenOfficeAuthTokens = Models.Row & {
  token: string;
};

export type SitePages = Models.Row & {
  slug: string;
  status: string | null;
};

export type BugReports = Models.Row & {
  description: string | null;
  user_id: string;
  user: Users;
  images: string[] | null;
};

export type TaxCodes = Models.Row & {
  code: string;
  name: string;
  rate: number;
  active: boolean;
};

export type ContentEntries = Models.Row & {
  kind: ContentEntriesKind;
  path: string | null;
  status: ContentEntriesStatus;
  visibility: ContentEntriesVisibility;
  scope: ContentEntriesScope;
  source_locale: ContentEntriesSourceLocale;
  template_id: string;
  campus_id: string | null;
  department_id: string | null;
  created_by: string | null;
};

export type ContentTemplates = Models.Row & {
  key: string;
  name: string;
  family: ContentTemplatesFamily;
  description: string | null;
  created_by: string | null;
  current_draft_version_id: string | null;
  current_published_version_id: string | null;
};

export type Teams = Models.Row & {
  name: string;
  total: number;
  members: string[];
};

export type DashboardMetrics = Models.Row & {
  metric_type: string;
  metric_data: string;
  date_range: string;
  computed_at: string;
};

export type StudentIds = Models.Row & {
  user: Users;
  student_id: string;
  expiry_date: string | null;
  isMember: boolean;
  memberships: Memberships[];
  membership_ids: string[] | null;
};

export type PageTranslations = Models.Row & {
  page: Pages;
  page_id: string;
  locale: PageTranslationsLocale | null;
  puck_document: string | null;
  draft_document: string | null;
  is_published: boolean;
  published_at: string | null;
  title: string;
  description: string | null;
};

export type ContentEntryLocales = Models.Row & {
  entry_id: string;
  locale: ContentEntryLocalesLocale;
  title: string;
  description: string | null;
  field_values: string | null;
  seo: string | null;
  translation_status: ContentEntryLocalesTranslationStatus;
  translated_from_locale: ContentEntryLocalesTranslatedFromLocale | null;
  source_updated_at: string | null;
};

export type FollowedUnits = Models.Row & {
  user_id: string;
  department_ids: string[] | null;
};

export type TypingIndicators = Models.Row & {
  chat_id: string;
  user_id: string;
  user_name: string;
  is_typing: boolean;
  expires_at: string;
};

export type Notifications = Models.Row & {
  status: NotificationsStatus;
};

export type FeatureFlags = Models.Row & {
  key: string;
  enabled: boolean;
  description: string | null;
  title: string;
};

export type ShopSettings = Models.Row & {
  general: string | null;
};

export type ProductFavorites = Models.Row & {
  user_id: string;
  product: Products;
};

export type CampusDataTranslations = Models.Row & {
  entry_id: string;
  locale: string;
  name: string | null;
  description: string | null;
  location: string | null;
  studentBenefits: string[] | null;
  careerAdvantages: string[] | null;
  socialNetwork: string[] | null;
  safety: string[] | null;
  businessBenefits: string[] | null;
  data: string | null;
};

export type SavedJobs = Models.Row & {
  jobId: number;
  title: string;
  campus: Campus[];
  user: Users[];
};

export type TourProgress = Models.Row & {
  user_id: string;
  tour_id: string;
  status: TourProgressStatus;
  step_index: number;
  version: number;
  completed_at: string | null;
};

export type Chats = Models.Row & {
  name: string;
  description: string | null;
  type: ChatsType;
  participants: string[];
  team_id: string | null;
  department_id: string | null;
  is_active: boolean;
  is_muted: boolean;
  unread_count: number;
  last_activity_at: string | null;
};

export type BenefitPartners = Models.Row & {
  name: string;
  website_url: string | null;
  logo_url: string | null;
  description_nb: string | null;
  description_en: string | null;
  campus_id: string | null;
  is_active: boolean;
};

export type Payments = Models.Row & {
  reference: string;
  amount: number;
  description: string | null;
  membership_id: string | null;
  membership: Memberships;
  status: string | null;
  paid_amount: number | null;
  user: Users;
  payment_method: string | null;
  user_id: string | null;
};

export type ChatMessages = Models.Row & {
  chat_id: string;
  sender_id: string;
  sender_name: string;
  content: string;
  type: ChatMessagesType;
  attachments: string[] | null;
  is_edited: boolean;
  is_deleted: boolean;
  reply_to_id: string | null;
};

export type Products = Models.Row & {
  name: string;
  description: string;
  price: number;
  currency: string;
  seller_id: string;
  seller_name: string;
  seller_avatar: string | null;
  campus_id: string;
  category: string;
  images: string[] | null;
  condition: ProductsCondition;
  status: ProductsStatus;
  is_negotiable: boolean;
  contact_method: ProductsContactMethod | null;
  contact_info: string | null;
  view_count: number;
  favorite_count: number;
  image_file_ids: string[] | null;
  favorites: ProductFavorites[];
};

export type ContentTemplateVersions = Models.Row & {
  template_id: string;
  version: number;
  status: ContentTemplateVersionsStatus;
  layout_document: string;
  field_schema: string;
  bindings: string;
  preview_seed_data: string | null;
  notes: string | null;
  published_at: string | null;
};

export type Pages = Models.Row & {
  status: PagesStatus;
  slug: string | null;
  campus_id: string | null;
  campus: Campus;
  visibility: PagesVisibility;
  department_id: string | null;
  translation_refs: PageTranslations[];
};

export type FormSubmissions = Models.Row & {
  page_id: string | null;
  topic: string;
  form_heading: string | null;
  data_json: string;
  status: FormSubmissionsStatus;
  access_team_id: string | null;
  campus_id: string | null;
  source: FormSubmissionsSource;
};

export type RecruitmentBookingTokens = Models.Row & {
  application_id: string;
  token_hash: string;
  panel_user_ids: string | null;
  duration_minutes: number;
  window_from: string;
  window_to: string;
  expires_at: string;
  consumed_at: string | null;
  interview_id: string | null;
  created_by_user_id: string | null;
  claim_lock: number;
};

export type JobApplicationAnswers = Models.Row & {
  application_id: string;
  job_id: string;
  question_id: string;
  question_label: string;
  answer_type: JobApplicationAnswersAnswerType;
  answer: string | null;
  application: JobApplications;
};

export type JobInterviews = Models.Row & {
  application_id: string;
  job_id: string;
  campus_id: string;
  department_id: string | null;
  round: number;
  title: string;
  starts_at: string | null;
  ends_at: string | null;
  timezone: string;
  location: string | null;
  meeting_url: string | null;
  teams_meeting_id: string | null;
  outlook_event_id: string | null;
  status: JobInterviewsStatus;
  notes: string | null;
  created_by_user_id: string | null;
  cancelled_reason: string | null;
  application: JobApplications;
  participants: JobInterviewParticipants[];
  scorecards: JobInterviewScorecards[];
};

export type JobInterviewParticipants = Models.Row & {
  interview_id: string;
  user_id: string | null;
  email: string;
  display_name: string | null;
  role: JobInterviewParticipantsRole;
  response_status: JobInterviewParticipantsResponseStatus;
  is_lead: boolean;
  interview: JobInterviews;
};

export type CandidateProfiles = Models.Row & {
  email: string;
  full_name: string;
  phone: string | null;
  linkedin_url: string | null;
  current_role: string | null;
  current_employer: string | null;
  campus_id: string | null;
  tags: string | null;
  gdpr_consent: boolean;
  consent_date: string;
  data_retention_until: string;
  last_application_at: string | null;
  applications_count: number;
  notes: string | null;
  source: string | null;
  embedding_status: CandidateProfilesEmbeddingStatus;
  embedding_id: string | null;
  applications: JobApplications[];
};

export type JobInterviewScorecards = Models.Row & {
  interview_id: string;
  application_id: string;
  interviewer_user_id: string;
  submitted_at: string | null;
  overall_score: number | null;
  recommendation: JobInterviewScorecardsRecommendation | null;
  criteria: string | null;
  strengths: string | null;
  concerns: string | null;
  private_notes: string | null;
  interview: JobInterviews;
};

export type StopPlaces = Models.Row & {
  stopPlaceId: string;
  name: string | null;
  enabled: boolean;
  campus_id: string;
};

export type Departures = Models.Row & {
  stopPlaceId: string;
  stopPlaceName: string | null;
  updatedAt: string;
  estimatedCalls: string | null;
};

export type ApprovalRequests = Models.Row & {
  requester_id: string;
  requester_email: string;
  action: string;
  resource_type: string;
  resource_id: string | null;
  payload: string;
  campus_id: string | null;
  department_id: string | null;
  approver_team_id: string;
  status: ApprovalRequestsStatus;
  decided_by: string | null;
  decided_at: string | null;
  reason: string | null;
};

export type Announcements = Models.Row & {
  status: AnnouncementsStatus;
  category: string;
  audience_type: AnnouncementsAudienceType;
  title_en: string;
  title_no: string | null;
  audience_value: string | null;
  body_en: string | null;
  body_no: string | null;
  event_id: string | null;
  campus_id: string | null;
  deep_link: string | null;
  data: string | null;
  push: boolean;
  scheduled_at: string | null;
  sent_at: string | null;
  created_by: string | null;
};

export type UserNotifications = Models.Row & {
  user_id: string;
  announcement_id: string;
  read: boolean;
};

export type EventSegments = Models.Row & {
  event_id: string | null;
  kind: string | null;
  name: string;
  campus_id: string | null;
  capacity: number;
  metadata: string | null;
  topic_id: string | null;
};

export type EventAttendees = Models.Row & {
  event_id: string;
  email: string | null;
  name: string | null;
  phone: string | null;
  ticket_type: string | null;
  order_ref: string | null;
  source: string;
  matched_user_id: string | null;
  campus_id: string | null;
};

export type SegmentMembers = Models.Row & {
  segment_id: string;
  event_id: string | null;
  user_id: string;
  attendee_id: string | null;
  assigned_at: string | null;
};

export type M365RemediationSnapshot = Models.Row & {
  generated_at: string;
  generated_by: string | null;
  total_scanned: number;
  safe_count: number;
  review_count: number;
  manual_count: number;
  closed_count: number;
  result: string | null;
};

export type M365TurnoverJobs = Models.Row & {
  user_id: string;
  user_upn: string;
  previous_display_name: string | null;
  new_display_name: string;
  new_given_name: string | null;
  new_surname: string | null;
  initiated_by_user_id: string | null;
  retention_started_at: string | null;
  retention_stop_at: string;
  status: M365TurnoverJobsStatus;
  stop_attempts: number;
  last_error: string | null;
};

export type PaymentSettings = Models.Row & {
  provider: PaymentSettingsProvider | null;
  test_mode: boolean;
  vipps_test_client_id: string | null;
  vipps_test_client_secret: string | null;
  vipps_test_subscription_key: string | null;
  vipps_test_msn: string | null;
  vipps_live_client_id: string | null;
  vipps_live_client_secret: string | null;
  vipps_live_subscription_key: string | null;
  vipps_live_msn: string | null;
  stripe_test_secret_key: string | null;
  stripe_test_webhook_secret: string | null;
  stripe_live_secret_key: string | null;
  stripe_live_webhook_secret: string | null;
  vipps_test_webhook_secret: string | null;
  vipps_live_webhook_secret: string | null;
};

export type LedgerAccounts = Models.Row & {
  account_number: number;
  name: string | null;
  tax_code: number | null;
  active: boolean;
  synced_at: string | null;
};

export type ExpenseCostTypes = Models.Row & {
  label: string;
  slug: string;
  description: string | null;
  ocr_category: string | null;
  account_number: number;
  tax_code: number | null;
  campus_id: string | null;
  sort_order: number;
  active: boolean;
};

export type ExpenseApprovals = Models.Row & {
  expense_id: string;
  step: number;
  approver_role: ExpenseApprovalsApproverRole;
  approver_email: string;
  approver_aad_id: string | null;
  status: ExpenseApprovalsStatus;
  decided_by: string | null;
  decided_at: string | null;
  reason: string | null;
  teams_conversation_id: string | null;
  teams_activity_id: string | null;
  token_hash: string;
  expires_at: string;
  consumed_at: string | null;
  campus_id: string | null;
  department: string | null;
  decision_lock: number;
};

export type ExpenseApprovalIssues = Models.Row & {
  expense_id: string | null;
  campus_id: string | null;
  role_sought: string | null;
  reason: string | null;
  status: ExpenseApprovalIssuesStatus;
  resolved_by: string | null;
  resolved_at: string | null;
  department: string | null;
};

export type AuthTokens = Models.Row & {
  token: string;
};
