// Ad-hoc department abbreviations found in BISO role-mailbox local-parts, mapped
// to the (campus-agnostic) department name. The resolver injects these into the
// model prompt; the model still chooses the campus-prefixed canonical candidate
// that matches (e.g. "kd" → "OSL Karrieredagene"). Only CONFIRMED mappings live
// here — uncertain ones intentionally fall through to review/manual.
//
// This is the single source of truth for the glossary; keep it in sync with the
// team's abbreviations reference.
export const DEPARTMENT_ABBREVIATIONS: Record<string, string> = {
  kd: "Karrieredagene",
  karrieredagene: "Karrieredagene",
  nu: "Næringslivsutvalget",
  nlu: "Næringslivsuken",
  fr: "Fadderullan",
  fadderullan: "Fadderullan",
  mu: "Markedsutvalget",
  mrk: "Markedsføring (linjeforening)",
  markedsutvalget: "Markedsutvalget",
  su: "Sosialutvalget",
  spu: "Studentpolitisk utvalg",
  vl: "Vinterlekene (Wintergames)",
  vinterlekene: "Vinterlekene (Wintergames)",
  wintergames: "Vinterlekene (Wintergames)",
  kk: "Kontrollkomiteen (Control Committee)",
  hr: "HR",
  accounting: "Accounting Department",
  media: "Media",
  bisomedia: "Media",
  charity: "Charity",
  charityball: "Charity (Charity Ball)",
  start: "Start BI",
  startbi: "Start BI",
  venturecup: "Start BI (Venture Cup)",
  inspire: "Inspire",
  fagutvalget: "Fagutvalget",
  fa: "Fagutvalget",
  bisi: "BISI – BI Student Idrett (overført til BIA)",
  idrett: "BISI – BI Student Idrett",
  bia: "BI Athletics (ekstern organisasjon)",
  biathletics: "BI Athletics (ekstern organisasjon)",
  invest: "Invest",
  aksje: "Aksjeklubben",
  aksjeklubben: "Aksjeklubben",
  aktie: "Børsgruppen Aktie",
  bull: "Bull Invest",
  peib: "PEIB – Private Equity Investment Banking Group",
  pieb: "PEIB – Private Equity Investment Banking Group",
  wif: "Women in Finance",
  famfa: "Femmes Fatales (FAMFA)",
  fbf: "Female Business Forum (FBF)",
  "bsc.finance": "FINANS (bachelor)",
  "msc.finance": "MSc Finans",
  sf: "MSc Sustainable Finance",
  okad: "ØKAD – Økonomi & Administrasjon",
  jusok: "JUSØK – Forretningsjus & Økonomi",
  okjus: "JUSØK – Forretningsjus & Økonomi",
  "bsc.jusok": "JUSØK – Forretningsjus & Økonomi",
  juss: "Forretningsjus",
  law: "Law Society",
  mrr: "MRR Master (Regnskap & Revisjon)",
  makro: "Makroøkonomisk Utvalg",
  entrep: "Entreprenørskap",
  "msc.entrep": "Entrep Master",
  cim: "CIM – Creative Industry Management",
  im: "IM – International Management",
  ems: "EMS – Eiendomsmeglerstyret",
  eiendom: "Eiendomsutvalget",
  eu: "Eiendomsutvalget",
  dsb: "Data Science Bachelor",
  db: "Digital Business",
  digicom: "DIGI-KOMM – Digital kommunikasjon og markedsføring",
  digcom: "DIGI-KOMM – Digital kommunikasjon og markedsføring",
  "msc.digicomm": "MSc Digicomm",
  mfl: "MFL – Markedsføringsledelse",
  smm: "SMM – Strategic Marketing Management",
  "smm.luiss": "SMM – Strategic Marketing Management (LUISS)",
  bba: "BBA – Bachelor of Business Administration",
  baa: "BAA – Business Analytics Association",
  org: "Organisasjonspsykologi, HR og ledelse",
  master: "LOP & Business Master Association",
  retail: "Retail Management",
  bims: "BIMS – BI Muslimske Studentsamfunn",
  bimss: "BIMS – BI Muslimske Studentsamfunn",
  biisa: "BIISA",
  gss: "GSS – Graduate Student Society",
  aiesec: "AIESEC",
  impact: "Impact",
  web3: "Web3",
  outdoor: "Outdoor",
  music: "Music Society",
  chess: "Chess",
  pride: "Pride",
  cards: "Cards",
  salute: "Salute – Wine Society",
  kollektivet: "Kollektivet",
  hvetevenner: "Hvetevenner",
  sleague: "Sunday League",
  caseclub: "Case Club",
  debate: "Debate Club",
  shipping: "Shipping (Society / Shippingutvalget)",
  car: "Car Society",
  creative: "Creative Society",
  ctech: "Creative Tech Society",
  bathing: "Bathing",
  "duck.bathing": "Bathing (Duck Bathing)",
  event: "Event Committee",
  bbl: "Bergensbaneløpet",
  bergensbanelopet: "Bergensbaneløpet",
  advisor: "Business Advisors",
  bc: "Business Connect",
  businessconnect: "Business Connect",
  connect: "Business Connect",
  da: "DataAnalytisk Utvalg",
  ufda: "UFDA",
  stauren: "Stauren Extreme",
  revy: "BI Revyen",
  gourmet: "Gourmetlaget",
  politics: "Politics / Academic-Political Forum",
  academics: "Academics / Academic-Political Forum",
  bar: "Bar Society",
  edge: "Edge",
  logistics: "Logistics Society",
  f1: "Formula 1 Society",
  formel1: "Formel 1",
  marketing: "Marketing",
  bargames: "Bar Games",
  trivia: "Trivia Night",
  bottiglia: "Bottiglia",
  mannskor: "Mannskor",
  paintnsip: "Paint n Sip",
  paint: "Paint n Sip",
  rederiet: "Rederiet",
  strikk: "Strikkevenner",
  strikkevenner: "Strikkevenner",
  seafood: "Seafood",
  beats: "Beats",
  society: "Society",
  bisosociety: "Society",
  equality: "Equality @ BI",
  korkutvalget: "Korkutvalget",
  ballers: "Ballers",
  porter: "Porter",
  baerekraft: "Bærekraft",
  fjos: "FJØS",
  karrierestigen: "Karrierestigen",
  lim: "LIM",
  emg: "EMG",
  oaf: "ØAF",
  golfgrill: "Golf & Grill",
  padel: "Padel",
  assistant: "Assistent",
  assistent: "Assistent",
  "hr.linjeforening": "HR Linjeforening",
  "mrk.linjeforening": "Markedsføring (linjeforening)",
  "okad.linjeforening": "Økonomi og Administrasjon (linjeforening)",
  "fjos.linjeforening": "FJØS (linjeforening)",
  board: "Board",
  fundscommittee: "Investment Committee",
  kroa: "Kroa (studentbar/drift)",
  golf: "Golf (sport, overført til BIA)",
  badminton: "Badminton (sport, overført til BIA)",
  running: "Running (sport, overført til BIA)",
  tennis: "Tennis (sport, overført til BIA)",
  volleyball: "Volleyball (sport, overført til BIA)",
  innebandy: "Innebandy (sport, overført til BIA)",
  handball: "Håndball (sport, overført til BIA)",
  fotball: "Fotball (sport, overført til BIA)",
  cheerleading: "Cheerleading (sport, overført til BIA)",
  amerikanskfotball: "Amerikansk fotball (sport, overført til BIA)",
};
