name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'packages/**'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Appwrite CLI
        run: npm install -g appwrite-cli

      - name: Deploy Full Repo to Appwrite
        env:
          APPWRITE_ENDPOINT: 'https://cloud.appwrite.io/v1'
          APPWRITE_PROJECT: ${{ secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_KEY: ${{ secrets.APPWRITE_API_KEY }}
        run: |
          appwrite sites create-deployment \
            --siteId ${{ secrets.API_SITE_ID }} \
            --code . \
            --activate true